name: "deploy"

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - env:
                  SSH_KEY: ${{ secrets.SSH_KEY }}
                  HOSTNAME: ${{ secrets.HOSTNAME }}
                  USERNAME: ${{ secrets.USERNAME }}
              run: |
                  ./scripts/deploy.sh frontend
    deploy-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - env:
                  SSH_KEY: ${{ secrets.SSH_KEY }}
                  HOSTNAME: ${{ secrets.HOSTNAME }}
                  USERNAME: ${{ secrets.USERNAME }}
              run: |
                  ./scripts/deploy.sh backend
